# Generated by Django 5.2.1 on 2025-06-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
